names(siDat[[currentBehavior]]$cln)[1] <- 'ResponseID ';
names(siDat[[currentBehavior]]$cln)[2] <- 'ResponseSet';
names(siDat[[currentBehavior]]$cln)[3] <- 'Name ';
names(siDat[[currentBehavior]]$cln)[4] <- 'ExternalDataReference  ';
names(siDat[[currentBehavior]]$cln)[5] <- 'EmailAddress  ';
names(siDat[[currentBehavior]]$cln)[6] <- 'IPAddress  ';
names(siDat[[currentBehavior]]$cln)[7] <- 'Status  ';
names(siDat[[currentBehavior]]$cln)[8] <- 'StartDate  ';
names(siDat[[currentBehavior]]$cln)[9] <- 'EndDate ';
names(siDat[[currentBehavior]]$cln)[10] <- 'Finished';
names(siDat[[currentBehavior]]$cln)[11] <- 'informedConsent';
names(siDat[[currentBehavior]]$cln)[12] <- 'age';
names(siDat[[currentBehavior]]$cln)[13] <- 'studyExit';
names(siDat[[currentBehavior]]$cln)[14] <- 'sex';
names(siDat[[currentBehavior]]$cln)[15] <- 'country';
names(siDat[[currentBehavior]]$cln)[16] <- 'information';
names(siDat[[currentBehavior]]$cln)[17] <- 'Intention_intend';
names(siDat[[currentBehavior]]$cln)[18] <- 'Intention2willing';
names(siDat[[currentBehavior]]$cln)[19] <- 'Intention3expect';
names(siDat[[currentBehavior]]$cln)[20] <- 'curBeh';
names(siDat[[currentBehavior]]$cln)[21] <- 'Attitude_bad_good';
names(siDat[[currentBehavior]]$cln)[22] <- 'Attitude_unpleasant_pleasant';
names(siDat[[currentBehavior]]$cln)[23] <- 'Attitude_harmful_beneficial';
names(siDat[[currentBehavior]]$cln)[24] <- 'Attitude_boring_interesting';
names(siDat[[currentBehavior]]$cln)[25] <- 'Importancescale_unimportant_important';
names(siDat[[currentBehavior]]$cln)[26] <- 'Importancescale_notessential_essential';
names(siDat[[currentBehavior]]$cln)[27] <- 'Importancescale_notsignificant_significant';
names(siDat[[currentBehavior]]$cln)[28] <- 'information';
names(siDat[[currentBehavior]]$cln)[29] <- 'Injunctivenorm_importantpeople';
names(siDat[[currentBehavior]]$cln)[30] <- 'Injunctivenorm_mostpeopleapprove';
names(siDat[[currentBehavior]]$cln)[31] <- 'Descriptivenorm_closefriends';
names(siDat[[currentBehavior]]$cln)[32] <- 'Descriptivenorm_peoplelikeme';
names(siDat[[currentBehavior]]$cln)[33] <- 'Perceivedcontrol_forme';
names(siDat[[currentBehavior]]$cln)[34] <- 'Perceivedcontrol_reallywantto';
names(siDat[[currentBehavior]]$cln)[35] <- 'Perceivedcontrol_confident';
names(siDat[[currentBehavior]]$cln)[36] <- 'information';
names(siDat[[currentBehavior]]$cln)[37] <- 'Selfidentity_rarelythinkabout';
names(siDat[[currentBehavior]]$cln)[38] <- 'Selfidentity_kindofperson';
names(siDat[[currentBehavior]]$cln)[39] <- 'Selfidentity_exercisingenoughimportant';
names(siDat[[currentBehavior]]$cln)[40] <- 'Selfidentity_notthinkingaboutexercisingregularly';
names(siDat[[currentBehavior]]$cln)[41] <- 'Selfidentity_seemyselfas';
names(siDat[[currentBehavior]]$cln)[42] <- 'Selfidentity_concernedwithnotdoingthebehaviorenough';
names(siDat[[currentBehavior]]$cln)[43] <- 'Selfidentity_doingbehaviorimportant';
names(siDat[[currentBehavior]]$cln)[44] <- 'Selfidentity_importantpart';
names(siDat[[currentBehavior]]$cln)[45] <- 'Selfidentity_seemyselffollowingthebehaviorguideline';
names(siDat[[currentBehavior]]$cln)[46] <- 'Selfidentity_wouldfeelatalossgivingupwrongbehavior';
names(siDat[[currentBehavior]]$cln)[47] <- 'Selfidentity_lossgivingupexercising';
names(siDat[[currentBehavior]]$cln)[48] <- 'Selfidentity_concernedwithdoingtherightbehavior';
names(siDat[[currentBehavior]]$cln)[49] <- 'Selfidentity_exercisingenoughmeansmore';
names(siDat[[currentBehavior]]$cln)[50] <- 'Selfidentity_wrongbehaviormeansmorethanjusttheact';
names(siDat[[currentBehavior]]$cln)[51] <- 'Selfidentity_behaviormeansmoretantheactself';
names(siDat[[currentBehavior]]$cln)[52] <- 'information';
names(siDat[[currentBehavior]]$cln)[53] <- 'Past_haveused';
names(siDat[[currentBehavior]]$cln)[54] <- 'Past_howoften';
names(siDat[[currentBehavior]]$cln)[55] <- 'VerificationWorkerID';
names(siDat[[currentBehavior]]$cln)[56] <- 'Endscreen';
names(siDat[[currentBehavior]]$cln)[57] <- 'Browser.Meta.Info.Browser ';
names(siDat[[currentBehavior]]$cln)[58] <- 'Browser.Meta.Info.Version ';
names(siDat[[currentBehavior]]$cln)[59] <- 'Browser.Meta.Info.Operating.System ';
names(siDat[[currentBehavior]]$cln)[60] <- 'Browser.Meta.Info.Screen.Resolution';
names(siDat[[currentBehavior]]$cln)[61] <- 'Browser.Meta.Info.Flash.Version ';
names(siDat[[currentBehavior]]$cln)[62] <- 'Browser.Meta.Info.Java.Support  ';
names(siDat[[currentBehavior]]$cln)[63] <- 'Browser.Meta.Info.User.Agent ';
names(siDat[[currentBehavior]]$cln)[64] <- 'LocationLatitude ';
names(siDat[[currentBehavior]]$cln)[65] <- 'LocationLongitude';
names(siDat[[currentBehavior]]$cln)[66] <- 'LocationAccuracy ';