---
title: "Self Identity Literature Synthesis"
author: "Marwin Snippe & Gjalt-Jorn Ygram Peters"
date: "`r format(Sys.time(), '%d %b %Y at %H:%M:%S');`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE);

################################################################################
### Load packages
################################################################################

require('userfriendlyscience');
require('metabefor');
safeRequire('readxl');
safeRequire('igraph');
safeRequire('ggplot2');
safeRequire('here');
safeRequire('tidyverse');
safeRequire('ggrepel');

######################################################################
### Set the variables with the paths (from before here::here()
######################################################################

### Select first existing path as base path
repoPath <- here::here();
workingPath <- here::here();

### Bibliomethics data file
bibliometricsDatafile <-
  file.path(repoPath,
            "overview-ascendency-descendency.xlsx");

```

```{r load-bibliography}

######################################################################
### Load datafile
######################################################################

dat <- read_excel(bibliometricsDatafile);

######################################################################
### Function to create unique identifier
######################################################################

uniqueIdentifier <- function(author, year, title,
                             bibtexAuthors = FALSE,
                             glue = "-") {
  if (bibtexAuthors) {
    ### Remove first names from author names
    author <- gsub(",[a-zA-Z \\.]+and", "-", author);
    ### Replace first names and initials of last author
    author <- gsub(",.*", "", author);
    
    ### Remove spaces
    author <- gsub(" ", "", author);
  } else {
    ### Remove initials from author names
    author <- gsub("[A-Z]\\.", "", author);
    ### Remove all non-letters and replace them by a dash
    author <- gsub("[^a-zA-Z]+", "-", author);
  }
  ### Substitute upper case letters with lower case letters
  author <- tolower(author);
  ### Remove dash at the end, where present
  author <- gsub("\\-$", "", author);
  ### Add year
  year <- paste0("--", year, "--");
  ### Remove initials from titles
  title <- gsub("[A-Z]\\.", "", title);
  ### Remove all non-letters and replace them by a dash
  title <- gsub("[^a-zA-Z]+", "-", title);
  ### Substitute upper case letters with lower case letters
  title <- tolower(title);
  ### Remove dash at the end, where present
  title <- gsub("\\-$", "", title);
  ### Combine all elements
  return(paste0(author,
                year,
                title));
};

######################################################################
### Generate unique identifiers for the children (citing articles)
######################################################################

dat$child_id <- uniqueIdentifier(author = dat$citingArticle_author,
                                 year = dat$citingArticle_year,
                                 title = dat$citingArticle_title);

######################################################################
### Generate unique identifiers for the parents (cited articles)
######################################################################

dat$parent_id <- uniqueIdentifier(author = dat$citedArticle_author,
                                  year = dat$citedArticle_year,
                                  title = dat$citedArticle_title,
                                  bibtexAuthors=TRUE);

######################################################################
### 'Minify' identifiers
######################################################################

suppressWarnings({
  dat$child_id_min <- abbreviate(gsub("\\-", "", dat$child_id),
                                 minlength=10);
  dat$parent_id_min <- abbreviate(gsub("\\-", "", dat$parent_id),
                                  minlength=10);
});

### Sort elements by year
dat$citingArticle_year_clean <-
  convertToNumeric(dat$citingArticle_year);

### Add sort order based on year and author of citing articles
dat$citingArticle_numericID <-
  order(dat$citingArticle_year_clean, dat$citingArticle_author);

dat <- as.data.frame(dat);

dat[dat$citingArticle_numericID, c('citingArticle_numericID',
                                   'citingArticle_year_clean',
                                   'citingArticle_author')];
#                                   'citingArticle_title')];

######################################################################
### Create scatterplot to show domains where each operationalisation
### type was applied
######################################################################

basedOnOriginalPapers <- 
  dat[dat$parent_id_min %in% c('sprkss1992', 'chrng1988r'), ];

basedOnOriginalPapers$origin <-
  ifelse(basedOnOriginalPapers$parent_id_min == 'sprkss1992',
         "Sparks1992",
         "Charng1998");

crossTab(basedOnOriginalPapers$citingArticle_topic,
         basedOnOriginalPapers$origin);

domainCitations <- table(basedOnOriginalPapers$citingArticle_topic,
                         basedOnOriginalPapers$origin) %>%
  data.frame() %>%
  spread('Var2', 'Freq');

names(domainCitations)[1] <- "Domain";

ggplot(domainCitations, aes_string(x = 'Sparks1992',
                                   y = 'Charng1998',
                                   label = 'Domain')) +
  geom_point(position = position_jitter()) +
  geom_text_repel();

######################################################################
### Graph
######################################################################

citNetDat <- dat[dat$child_id_min != 'NANANA', c('parent_id_min', 'child_id_min')];
#citNetDat$children <- 

citationNetwork <- graph.data.frame(citNetDat);

### Set attributes
vertex_attr(citationNetwork, "color") <- "grey";
vertex_attr(citationNetwork, "label.color") <- "black";
vertex_attr(citationNetwork, "label.family") <- "sans";
vertex_attr(citationNetwork, "size") <- 1;
vertex_attr(citationNetwork, "label.dist") <- .6;
vertex_attr(citationNetwork, "label.cex") <- 1.1; # font size

pdf(file = file.path(workingPath, "citation-network.pdf"),
    width=27, height=19);
plot(citationNetwork, size=60, width=40,
     asp=2/3);
dev.off()

```



